spring.application.name=backend
spring.datasource.url=jdbc:oracle:thin:@10.0.0.200:1521/XEPDB1
spring.datasource.username=meubolso
spring.datasource.password=MeuBolso@2026
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=meubolso
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

# JWT Config (Secret em Base64 - deve ser alterado em producao)
jwt.secret=MeuBolsoEnterpriseSecretKeyParaAssinaturaDeTokensMultiTenant
jwt.expiration=86400000
